home:
  path: /
  controller: App\Controller\HomeController::index

produit:
  path: /produit
  controller: App\Controller\ProduitController::index

admin:
  path: /admin
  controller: App\Controller\AdminProduitController::index

logout:
  path: /logout
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
