home:
  path: /
  controller: App\Controller\HomeController::index

produit:
  path: /produit
  controller: App\Controller\ProduitController::index

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
